---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: molecule-ubuntu
    image: "geerlingguy/docker-ubuntu2204-ansible:latest"
    privileged: true
    # command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
